"""
WMS Enterprise - Product Model
SKU Master with multi-code support and search keywords
"""
from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, Enum, JSON, ForeignKey, Numeric
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.models.enums import ProductCategory, ProductUnit


class Product(Base):
    """
    Product Master / SKU Master
    
    Supports multiple codes per product:
    - SKU Internal (toko)
    - Part Number (manufacturer)
    - Barcode
    - AI Scan code
    """
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    
    # Internal SKU - generated by system
    sku = Column(String(50), unique=True, index=True, nullable=False)
    
    # Basic info
    name = Column(String(200), nullable=False)
    description = Column(Text)
    brand = Column(String(50), index=True)
    
    # Category
    category = Column(
        Enum(ProductCategory, native_enum=False),
        default=ProductCategory.HOSE,
        nullable=False
    )
    
    # Serial Number Tracking (Phase 8)
    is_serialized = Column(Boolean, default=False)
    
    # BOM Relationship
    components = relationship("ProductComponent", foreign_keys="[ProductComponent.parent_product_id]", back_populates="parent_product")
    
    # Substitute Relationship (Phase 9)
    substitutes = relationship("ProductSubstitute", foreign_keys="[ProductSubstitute.product_id]", back_populates="product")
    
    # Unit of measurement
    unit = Column(
        Enum(ProductUnit, native_enum=False),
        default=ProductUnit.METER,
        nullable=False
    )
    
    # Search keywords - indexed for fast search
    # Contains: brand, sku, part numbers, aliases, etc.
    search_keywords = Column(Text, index=True)
    
    # Technical specifications as JSON
    # For hose: pressure, size, standard, wire_type, etc.
    specifications = Column(JSON, default={})
    
    # Pricing
    cost_price = Column(Integer)  # Rp per unit
    sell_price = Column(Integer)  # Rp per unit
    
    # Inventory settings
    min_stock = Column(Integer, default=0)
    max_stock = Column(Integer)
    reorder_point = Column(Integer)
    
    # Unit Conversion (for Gudang vs Toko)
    # Example: 1 ROLL = 50 METER
    alt_unit = Column(String(20))  # Alternative unit (ROLL, PCS, BOX)
    conversion_factor = Column(Numeric(10, 2))  # 1 alt_unit = X base_unit
    
    # Status
    is_active = Column(Boolean, default=True)
    is_sellable = Column(Boolean, default=True)
    is_purchasable = Column(Boolean, default=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    aliases = relationship("ProductAlias", back_populates="product", cascade="all, delete-orphan")
    batches = relationship("InventoryBatch", back_populates="product")
    
    def __repr__(self):
        return f"<Product {self.sku}: {self.name}>"
    
    def update_search_keywords(self):
        """Update search_keywords from all aliases and product info"""
        # Handle category - could be enum or string
        category_str = ""
        if self.category:
            category_str = self.category.value if hasattr(self.category, 'value') else str(self.category)
        
        keywords = [
            self.sku or "",
            self.name or "",
            self.brand or "",
            category_str,
        ]
        
        # Add aliases
        for alias in self.aliases:
            keywords.append(alias.alias_value or "")
        
        # Add specifications
        if self.specifications:
            for key, value in self.specifications.items():
                if value:
                    keywords.append(str(value))
        
        self.search_keywords = " ".join(keywords).upper()
    
    def convert_to_base_unit(self, alt_qty: float) -> float:
        """Convert from alt_unit to base_unit (e.g., ROLL → METER)"""
        if self.conversion_factor:
            return alt_qty * float(self.conversion_factor)
        return alt_qty
    
    def convert_to_alt_unit(self, base_qty: float) -> float:
        """Convert from base_unit to alt_unit (e.g., METER → ROLL)"""
        if self.conversion_factor and float(self.conversion_factor) > 0:
            return base_qty / float(self.conversion_factor)
        return base_qty
    
    def format_qty_with_alt(self, base_qty: float) -> str:
        """Format qty showing both units (e.g., '50m (1 Roll)')"""
        unit_str = self.unit.value if self.unit else ""
        if self.alt_unit and self.conversion_factor:
            alt_qty = self.convert_to_alt_unit(base_qty)
            return f"{base_qty}{unit_str} ({alt_qty:.1f} {self.alt_unit})"
        return f"{base_qty}{unit_str}"
    
    def to_dict(self):
        category_val = None
        if self.category:
            category_val = self.category.value if hasattr(self.category, 'value') else str(self.category)
            
        unit_val = None
        if self.unit:
            unit_val = self.unit.value if hasattr(self.unit, 'value') else str(self.unit)

        return {
            "id": self.id,
            "sku": self.sku,
            "name": self.name,
            "description": self.description,
            "brand": self.brand,
            "category": category_val,
            "unit": unit_val,
            "alt_unit": self.alt_unit,
            "conversion_factor": float(self.conversion_factor) if self.conversion_factor else None,
            "specifications": self.specifications,
            "cost_price": self.cost_price,
            "sell_price": self.sell_price,
            "min_stock": self.min_stock,
            "is_active": self.is_active,
            "aliases": [a.to_dict() for a in self.aliases] if self.aliases else [],
        }


class ProductAlias(Base):
    """
    Product Alias / Multi-Code Mapping
    
    One product can have multiple codes:
    - INTERNAL: SKU toko (FIT-EAT-001)
    - MANUFACTURER: Part number pabrik (1A-202-08)
    - BARCODE: Kode di fisik barang (B22910)
    - AI_SCAN: Kode dari AI Scanner
    """
    __tablename__ = "product_aliases"

    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign key to product
    product_id = Column(Integer, ForeignKey("products.id"), index=True, nullable=False)
    
    # Alias type
    alias_type = Column(String(20), nullable=False)
    
    # Alias value - indexed for search
    alias_value = Column(String(100), index=True, nullable=False)
    
    # Is this the primary code for this type?
    is_primary = Column(Boolean, default=False)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    product = relationship("Product", back_populates="aliases")
    
    def __repr__(self):
        return f"<ProductAlias {self.alias_type}: {self.alias_value}>"
    
    def to_dict(self):
        return {
            "id": self.id,
            "alias_type": self.alias_type,
            "alias_value": self.alias_value,
            "is_primary": self.is_primary,
        }
