"""Add InterCompanyLoan B2B models

Revision ID: 72937a9cbf04
Revises: a53d55c0a9fb
Create Date: 2026-03-02 11:16:37.115117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72937a9cbf04'
down_revision: Union[str, Sequence[str], None] = 'a53d55c0a9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intercompany_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sa.String(length=50), nullable=False),
    sa.Column('from_company_id', sa.Integer(), nullable=False),
    sa.Column('to_company_id', sa.Integer(), nullable=False),
    sa.Column('loan_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercompany_loans_from_company_id'), 'intercompany_loans', ['from_company_id'], unique=False)
    op.create_index(op.f('ix_intercompany_loans_id'), 'intercompany_loans', ['id'], unique=False)
    op.create_index(op.f('ix_intercompany_loans_loan_number'), 'intercompany_loans', ['loan_number'], unique=True)
    op.create_index(op.f('ix_intercompany_loans_to_company_id'), 'intercompany_loans', ['to_company_id'], unique=False)
    op.create_table('intercompany_loan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_sku', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('qty_loaned', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qty_returned', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('qty_sold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['intercompany_loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['inventory_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercompany_loan_items_id'), 'intercompany_loan_items', ['id'], unique=False)
    op.create_index(op.f('ix_intercompany_loan_items_loan_id'), 'intercompany_loan_items', ['loan_id'], unique=False)
    op.drop_index(op.f('ix_rma_tickets_customer_name'), table_name='rma_tickets')
    op.drop_index(op.f('ix_rma_tickets_id'), table_name='rma_tickets')
    op.drop_index(op.f('ix_rma_tickets_ticket_number'), table_name='rma_tickets')
    op.drop_table('rma_tickets')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tax_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_formats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operations_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('security_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_from_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wa_sender_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('printer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_password_enc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wa_api_key_enc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('system_settings_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_table('rma_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'RECEIVED', 'INSPECTION', 'DECIDED', 'CLOSED', name='rmastatus'), autoincrement=False, nullable=True),
    sa.Column('root_cause', postgresql.ENUM('ASSEMBLY_ERROR', 'MATERIAL_DEFECT', 'CUSTOMER_MISUSE', 'OTHER', name='rmarootcause'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('solution', postgresql.ENUM('REPLACE', 'REFUND', 'REJECTED', 'REPAIR', name='rmasolution'), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rma_tickets_pkey'))
    )
    op.create_index(op.f('ix_rma_tickets_ticket_number'), 'rma_tickets', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_rma_tickets_id'), 'rma_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_rma_tickets_customer_name'), 'rma_tickets', ['customer_name'], unique=False)
    op.drop_index(op.f('ix_intercompany_loan_items_loan_id'), table_name='intercompany_loan_items')
    op.drop_index(op.f('ix_intercompany_loan_items_id'), table_name='intercompany_loan_items')
    op.drop_table('intercompany_loan_items')
    op.drop_index(op.f('ix_intercompany_loans_to_company_id'), table_name='intercompany_loans')
    op.drop_index(op.f('ix_intercompany_loans_loan_number'), table_name='intercompany_loans')
    op.drop_index(op.f('ix_intercompany_loans_id'), table_name='intercompany_loans')
    op.drop_index(op.f('ix_intercompany_loans_from_company_id'), table_name='intercompany_loans')
    op.drop_table('intercompany_loans')
    # ### end Alembic commands ###
