"""\ add_crm_lead\

Revision ID: a53d55c0a9fb
Revises: cd38d8d6a6d8
Create Date: 2026-02-23 10:10:05.475975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a53d55c0a9fb'
down_revision: Union[str, Sequence[str], None] = 'cd38d8d6a6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    insp = sa.inspect(conn)
    tables = insp.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'crm_leads' not in tables:
        op.create_table('crm_leads',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('company_name', sa.String(length=200), nullable=False),
        sa.Column('contact_person', sa.String(length=100), nullable=True),
        sa.Column('contact_email', sa.String(length=100), nullable=True),
        sa.Column('contact_phone', sa.String(length=50), nullable=True),
        sa.Column('estimated_value', sa.Float(), nullable=True),
        sa.Column('status', sa.Enum('PROSPECT', 'NEGOTIATION', 'WON', 'LOST', name='leadstatus', native_enum=False), nullable=True),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
        op.create_index(op.f('ix_crm_leads_status'), 'crm_leads', ['status'], unique=False)
    op.drop_index('ix_rma_tickets_customer_name', table_name='rma_tickets', if_exists=True)
    op.drop_index('ix_rma_tickets_id', table_name='rma_tickets', if_exists=True)
    op.drop_index('ix_rma_tickets_ticket_number', table_name='rma_tickets', if_exists=True)
    if 'rma_tickets' in tables:
        op.drop_table('rma_tickets')
    op.drop_index('idx_refresh_tokens_family', table_name='refresh_tokens', if_exists=True)
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens', if_exists=True)
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens', if_exists=True)
    if 'refresh_tokens' in tables:
        op.drop_table('refresh_tokens')
    op.drop_index('ix_system_settings_id', table_name='system_settings', if_exists=True)
    if 'system_settings' in tables:
        op.drop_table('system_settings')
    op.drop_index('ix_stock_opname_items_id', table_name='stock_opname_items', if_exists=True)
    if 'stock_opname_items' in tables:
        op.drop_table('stock_opname_items')
    op.alter_column('batch_movements', 'movement_type',
               existing_type=postgresql.ENUM('INBOUND', 'OUTBOUND', 'TRANSFER', 'RESERVE', 'UNRESERVE', 'CONSUME', 'ADJUST_PLUS', 'ADJUST_MINUS', 'RETURN_IN', 'RETURN_OUT', 'SCRAP', 'ASSEMBLY_RESULT', name='movementtype'),
               type_=sa.Enum('INBOUND', 'OUTBOUND', 'TRANSFER', 'RESERVE', 'UNRESERVE', 'CONSUME', 'ADJUST_PLUS', 'ADJUST_MINUS', 'RETURN_IN', 'RETURN_OUT', 'ASSEMBLY_USE', 'ASSEMBLY_RESULT', 'SWAP_IN', 'SWAP_OUT', 'LOAN_OUT', 'LOAN_RETURN', 'SCRAP', name='movementtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('batch_movements', 'unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('batch_movements', 'total_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    try:
        op.create_foreign_key(None, 'customer_assets', 'customers', ['customer_id'], ['id'])
    except Exception: pass
    
    op.drop_index('ix_inventory_batches_owner_id', table_name='inventory_batches', if_exists=True)
    op.create_index(op.f('ix_invoices_salesman_id'), 'invoices', ['salesman_id'], unique=False, if_not_exists=True)
    
    try:
        op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'])
    except Exception: pass
    
    op.drop_index('idx_jo_lines_serial', table_name='jo_lines', if_exists=True)
    try:
        op.drop_constraint('jo_lines_serial_number_key', 'jo_lines', type_='unique')
    except Exception: pass
    
    op.create_index(op.f('ix_jo_lines_serial_number'), 'jo_lines', ['serial_number'], unique=True, if_not_exists=True)
    
    try:
        op.alter_column('landed_costs', 'po_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    except Exception: pass
    
    op.create_index(op.f('ix_landed_costs_id'), 'landed_costs', ['id'], unique=False, if_not_exists=True)
    
    try:
        op.create_foreign_key(None, 'landed_costs', 'purchase_orders', ['po_id'], ['id'])
    except Exception: pass
    
    try:
        op.create_foreign_key(None, 'payments', 'purchase_orders', ['po_id'], ['id'])
    except Exception: pass
    
    # price history columns
    try:
        if 'reason' not in [c['name'] for c in insp.get_columns('price_history')]:
            op.add_column('price_history', sa.Column('old_base_price', sa.Float(), nullable=True))
            op.add_column('price_history', sa.Column('new_base_price', sa.Float(), nullable=True))
            op.add_column('price_history', sa.Column('old_sell_price', sa.Float(), nullable=True))
            op.add_column('price_history', sa.Column('new_sell_price', sa.Float(), nullable=True))
            op.add_column('price_history', sa.Column('change_type', sa.Enum('MANUAL', 'BULK', 'IMPORT', name='pricechangetype'), nullable=True))
            op.add_column('price_history', sa.Column('reason', sa.String(length=500), nullable=True))
            op.alter_column('price_history', 'product_id', existing_type=sa.INTEGER(), nullable=False)
            op.drop_column('price_history', 'product_sku')
            op.drop_column('price_history', 'source_reference')
            op.drop_column('price_history', 'supplier_id')
            op.drop_column('price_history', 'supplier_name')
            op.drop_column('price_history', 'product_name')
            op.drop_column('price_history', 'valid_from')
            op.drop_column('price_history', 'valid_until')
            op.drop_column('price_history', 'source')
            op.drop_column('price_history', 'unit_price')
            op.drop_column('price_history', 'unit')
            op.drop_column('price_history', 'notes')
    except Exception: pass
    
    try:
        op.create_foreign_key(None, 'product_aliases', 'products', ['product_id'], ['id'])
    except Exception: pass
    
    try:
        op.create_foreign_key(None, 'product_loan_items', 'product_loans', ['loan_id'], ['id'])
    except Exception: pass

    # -- Remaining ALTER/DROP operations wrapped in try/except for idempotency --
    try:
        op.alter_column('products', 'category',
                   existing_type=postgresql.ENUM('HOSE', 'FITTING', 'ASSEMBLY', 'ACCESSORY', 'CONNECTOR', 'ADAPTER', name='productcategory'),
                   type_=sa.Enum('HYDRAULIC_HOSE', 'INDUSTRIAL_HOSE', 'SPECIALTY_HOSE', 'HOSE', 'CRIMP_FITTING', 'REUSABLE_FITTING', 'FITTING', 'ADAPTER', 'QUICK_COUPLING', 'CONNECTOR', 'HOSE_ASSEMBLY', 'ASSEMBLY', 'ACCESSORY', 'VALVE', 'PIPE_TUBE', 'TOOL', name='productcategory', native_enum=False),
                   existing_nullable=False)
    except Exception: pass
    try:
        op.alter_column('products', 'unit',
                   existing_type=postgresql.ENUM('METER', 'PCS', 'SET', 'ROLL', name='productunit'),
                   type_=sa.Enum('METER', 'PCS', 'SET', 'ROLL', 'BOX', 'KG', 'LITER', 'FEET', name='productunit', native_enum=False),
                   existing_nullable=False)
    except Exception: pass
    try:
        op.alter_column('products', 'form',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('FULL_ROLL', 'CUT_LENGTH', 'COIL', 'STRAIGHT', 'LOOSE', 'BOXED', 'ASSEMBLED', name='productform', native_enum=False),
                   existing_nullable=True,
                   existing_server_default=sa.text('NULL::character varying'))
    except Exception: pass
    try:
        op.drop_column('products', 'safety_stock')
    except Exception: pass
    try:
        op.drop_column('products', 'lead_time_days')
    except Exception: pass
    try:
        op.alter_column('sales_orders', 'status',
                   existing_type=postgresql.ENUM('DRAFT', 'CONFIRMED', 'PARTIAL_JO', 'FULL_JO', 'PARTIAL_DELIVERED', 'COMPLETED', 'CANCELLED', name='sostatus'),
                   type_=sa.Enum('DRAFT', 'PENDING_APPROVAL', 'CONFIRMED', 'PARTIAL_JO', 'FULL_JO', 'PARTIAL_DELIVERED', 'COMPLETED', 'INVOICED', 'CANCELLED', name='sostatus', native_enum=False),
                   existing_nullable=False)
    except Exception: pass
    op.create_index(op.f('ix_sales_orders_is_deleted'), 'sales_orders', ['is_deleted'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sales_orders_salesman_id'), 'sales_orders', ['salesman_id'], unique=False, if_not_exists=True)
    try:
        op.alter_column('stock_opnames', 'description',
                   existing_type=sa.VARCHAR(length=200),
                   nullable=False)
    except Exception: pass
    try:
        op.alter_column('stock_opnames', 'status',
                   existing_type=sa.VARCHAR(length=30),
                   type_=sa.Enum('OPEN', 'COMPLETED', 'CANCELLED', 'IN_PROGRESS', name='opnamestatus'),
                   nullable=False)
    except Exception: pass
    op.drop_index('ix_stock_opnames_opname_number', table_name='stock_opnames', if_exists=True)
    try:
        op.create_unique_constraint(None, 'stock_opnames', ['opname_number'])
    except Exception: pass
    try:
        op.drop_constraint('stock_opnames_location_id_fkey', 'stock_opnames', type_='foreignkey')
    except Exception: pass
    for col in ['items_under', 'items_matched', 'items_over', 'counted_by', 'notes', 'approved_by', 'total_variance_value', 'zone', 'location_id', 'opname_date']:
        try:
            op.drop_column('stock_opnames', col)
        except Exception: pass
    op.drop_index('ix_storage_locations_company_id', table_name='storage_locations', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_storage_locations_company_id', 'storage_locations', ['company_id'], unique=False)
    op.add_column('stock_opnames', sa.Column('opname_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('zone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('total_variance_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('approved_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('counted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('items_over', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('items_matched', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_opnames', sa.Column('items_under', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stock_opnames_location_id_fkey', 'stock_opnames', 'storage_locations', ['location_id'], ['id'])
    op.drop_constraint(None, 'stock_opnames', type_='unique')
    op.create_index('ix_stock_opnames_opname_number', 'stock_opnames', ['opname_number'], unique=True)
    op.alter_column('stock_opnames', 'status',
               existing_type=sa.Enum('OPEN', 'COMPLETED', 'CANCELLED', 'IN_PROGRESS', name='opnamestatus'),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('stock_opnames', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f('ix_sales_orders_salesman_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_is_deleted'), table_name='sales_orders')
    op.alter_column('sales_orders', 'status',
               existing_type=sa.Enum('DRAFT', 'PENDING_APPROVAL', 'CONFIRMED', 'PARTIAL_JO', 'FULL_JO', 'PARTIAL_DELIVERED', 'COMPLETED', 'INVOICED', 'CANCELLED', name='sostatus', native_enum=False),
               type_=postgresql.ENUM('DRAFT', 'CONFIRMED', 'PARTIAL_JO', 'FULL_JO', 'PARTIAL_DELIVERED', 'COMPLETED', 'CANCELLED', name='sostatus'),
               existing_nullable=False)
    op.add_column('products', sa.Column('lead_time_days', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('safety_stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('products', 'form',
               existing_type=sa.Enum('FULL_ROLL', 'CUT_LENGTH', 'COIL', 'STRAIGHT', 'LOOSE', 'BOXED', 'ASSEMBLED', name='productform', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('products', 'unit',
               existing_type=sa.Enum('METER', 'PCS', 'SET', 'ROLL', 'BOX', 'KG', 'LITER', 'FEET', name='productunit', native_enum=False),
               type_=postgresql.ENUM('METER', 'PCS', 'SET', 'ROLL', name='productunit'),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.Enum('HYDRAULIC_HOSE', 'INDUSTRIAL_HOSE', 'SPECIALTY_HOSE', 'HOSE', 'CRIMP_FITTING', 'REUSABLE_FITTING', 'FITTING', 'ADAPTER', 'QUICK_COUPLING', 'CONNECTOR', 'HOSE_ASSEMBLY', 'ASSEMBLY', 'ACCESSORY', 'VALVE', 'PIPE_TUBE', 'TOOL', name='productcategory', native_enum=False),
               type_=postgresql.ENUM('HOSE', 'FITTING', 'ASSEMBLY', 'ACCESSORY', 'CONNECTOR', 'ADAPTER', name='productcategory'),
               existing_nullable=False)
    op.drop_constraint(None, 'product_loan_items', type_='foreignkey')
    op.drop_constraint(None, 'product_aliases', type_='foreignkey')
    op.add_column('price_history', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('unit_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('price_history', sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('supplier_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('source_reference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('price_history', sa.Column('product_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('price_history', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('price_history', 'reason')
    op.drop_column('price_history', 'change_type')
    op.drop_column('price_history', 'new_sell_price')
    op.drop_column('price_history', 'old_sell_price')
    op.drop_column('price_history', 'new_base_price')
    op.drop_column('price_history', 'old_base_price')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'landed_costs', type_='foreignkey')
    op.drop_index(op.f('ix_landed_costs_id'), table_name='landed_costs')
    op.alter_column('landed_costs', 'po_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_jo_lines_serial_number'), table_name='jo_lines')
    op.create_unique_constraint('jo_lines_serial_number_key', 'jo_lines', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_jo_lines_serial', 'jo_lines', ['serial_number'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_salesman_id'), table_name='invoices')
    op.create_index('ix_inventory_batches_owner_id', 'inventory_batches', ['owner_id'], unique=False)
    op.drop_constraint(None, 'customer_assets', type_='foreignkey')
    op.alter_column('batch_movements', 'total_value',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('batch_movements', 'unit_cost',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('batch_movements', 'movement_type',
               existing_type=sa.Enum('INBOUND', 'OUTBOUND', 'TRANSFER', 'RESERVE', 'UNRESERVE', 'CONSUME', 'ADJUST_PLUS', 'ADJUST_MINUS', 'RETURN_IN', 'RETURN_OUT', 'ASSEMBLY_USE', 'ASSEMBLY_RESULT', 'SWAP_IN', 'SWAP_OUT', 'LOAN_OUT', 'LOAN_RETURN', 'SCRAP', name='movementtype', native_enum=False),
               type_=postgresql.ENUM('INBOUND', 'OUTBOUND', 'TRANSFER', 'RESERVE', 'UNRESERVE', 'CONSUME', 'ADJUST_PLUS', 'ADJUST_MINUS', 'RETURN_IN', 'RETURN_OUT', 'SCRAP', 'ASSEMBLY_RESULT', name='movementtype'),
               existing_nullable=False)
    op.create_table('stock_opname_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opname_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('location_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('system_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('counted_qty', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('variance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('variance_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], name='stock_opname_items_batch_id_fkey'),
    sa.ForeignKeyConstraint(['opname_id'], ['stock_opnames.id'], name='stock_opname_items_opname_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='stock_opname_items_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_opname_items_pkey')
    )
    op.create_index('ix_stock_opname_items_id', 'stock_opname_items', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tax_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_formats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operations_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('security_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_from_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wa_sender_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('printer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_password_enc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wa_api_key_enc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name='system_settings_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey')
    )
    op.create_index('ix_system_settings_id', 'system_settings', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
    sa.UniqueConstraint('token_hash', name='refresh_tokens_token_hash_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_table('rma_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'RECEIVED', 'INSPECTION', 'DECIDED', 'CLOSED', name='rmastatus'), autoincrement=False, nullable=True),
    sa.Column('root_cause', postgresql.ENUM('ASSEMBLY_ERROR', 'MATERIAL_DEFECT', 'CUSTOMER_MISUSE', 'OTHER', name='rmarootcause'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('solution', postgresql.ENUM('REPLACE', 'REFUND', 'REJECTED', 'REPAIR', name='rmasolution'), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rma_tickets_pkey')
    )
    op.create_index('ix_rma_tickets_ticket_number', 'rma_tickets', ['ticket_number'], unique=True)
    op.create_index('ix_rma_tickets_id', 'rma_tickets', ['id'], unique=False)
    op.create_index('ix_rma_tickets_customer_name', 'rma_tickets', ['customer_name'], unique=False)
    op.drop_index(op.f('ix_crm_leads_status'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    # ### end Alembic commands ###
