"""add_blanket_order

Revision ID: b0d504631498
Revises: 72937a9cbf04
Create Date: 2026-03-13 03:10:26.807565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d504631498'
down_revision: Union[str, Sequence[str], None] = '72937a9cbf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blanket_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.Column('release_number', sa.String(length=50), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('do_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'READY', 'RELEASED', 'DELIVERED', 'CANCELLED', name='blanketreleasestatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('released_by', sa.String(length=100), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['do_id'], ['delivery_orders.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blanket_releases_do_id'), 'blanket_releases', ['do_id'], unique=False)
    op.create_index(op.f('ix_blanket_releases_id'), 'blanket_releases', ['id'], unique=False)
    op.create_index(op.f('ix_blanket_releases_invoice_id'), 'blanket_releases', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_blanket_releases_release_number'), 'blanket_releases', ['release_number'], unique=True)
    op.create_index(op.f('ix_blanket_releases_so_id'), 'blanket_releases', ['so_id'], unique=False)
    op.create_index(op.f('ix_blanket_releases_status'), 'blanket_releases', ['status'], unique=False)
    op.create_table('blanket_release_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('so_line_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['blanket_releases.id'], ),
    sa.ForeignKeyConstraint(['so_line_id'], ['so_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blanket_release_lines_id'), 'blanket_release_lines', ['id'], unique=False)
    op.create_index(op.f('ix_blanket_release_lines_release_id'), 'blanket_release_lines', ['release_id'], unique=False)
    op.create_index(op.f('ix_blanket_release_lines_so_line_id'), 'blanket_release_lines', ['so_line_id'], unique=False)
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_rma_tickets_customer_name'), table_name='rma_tickets')
    op.drop_index(op.f('ix_rma_tickets_id'), table_name='rma_tickets')
    op.drop_index(op.f('ix_rma_tickets_ticket_number'), table_name='rma_tickets')
    op.drop_table('rma_tickets')
    op.add_column('sales_orders', sa.Column('order_type', sa.String(length=20), nullable=True))
    op.add_column('sales_orders', sa.Column('blanket_valid_from', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('blanket_valid_until', sa.Date(), nullable=True))
    op.add_column('sales_orders', sa.Column('qty_reserved', sa.Integer(), nullable=True))
    op.add_column('so_lines', sa.Column('qty_released', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('so_lines', 'qty_released')
    op.drop_column('sales_orders', 'qty_reserved')
    op.drop_column('sales_orders', 'blanket_valid_until')
    op.drop_column('sales_orders', 'blanket_valid_from')
    op.drop_column('sales_orders', 'order_type')
    op.create_table('rma_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('NEW', 'RECEIVED', 'INSPECTION', 'DECIDED', 'CLOSED', name='rmastatus'), autoincrement=False, nullable=True),
    sa.Column('root_cause', postgresql.ENUM('ASSEMBLY_ERROR', 'MATERIAL_DEFECT', 'CUSTOMER_MISUSE', 'OTHER', name='rmarootcause'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('solution', postgresql.ENUM('REPLACE', 'REFUND', 'REJECTED', 'REPAIR', name='rmasolution'), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rma_tickets_pkey'))
    )
    op.create_index(op.f('ix_rma_tickets_ticket_number'), 'rma_tickets', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_rma_tickets_id'), 'rma_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_rma_tickets_customer_name'), 'rma_tickets', ['customer_name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tax_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_formats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operations_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('security_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_from_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wa_sender_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('printer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smtp_password_enc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wa_api_key_enc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('system_settings_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.drop_index(op.f('ix_blanket_release_lines_so_line_id'), table_name='blanket_release_lines')
    op.drop_index(op.f('ix_blanket_release_lines_release_id'), table_name='blanket_release_lines')
    op.drop_index(op.f('ix_blanket_release_lines_id'), table_name='blanket_release_lines')
    op.drop_table('blanket_release_lines')
    op.drop_index(op.f('ix_blanket_releases_status'), table_name='blanket_releases')
    op.drop_index(op.f('ix_blanket_releases_so_id'), table_name='blanket_releases')
    op.drop_index(op.f('ix_blanket_releases_release_number'), table_name='blanket_releases')
    op.drop_index(op.f('ix_blanket_releases_invoice_id'), table_name='blanket_releases')
    op.drop_index(op.f('ix_blanket_releases_id'), table_name='blanket_releases')
    op.drop_index(op.f('ix_blanket_releases_do_id'), table_name='blanket_releases')
    op.drop_table('blanket_releases')
    # ### end Alembic commands ###
